### PR TITLE
Additional properties

### PR DESCRIPTION
**Pull request by MikhailPodkur**
Check box component with all functions added.
Cyrillic font 8*12 added.
65k color (2 byte per point) schema added.
Windows components font could be getted from current GUI by default

### CODE REVIEW

**Comment by achimdoebler** [comment]
Hi Mikhail, thanks for the nice improvements!
I will pull in all your new features, except some minor things.
What was the reason for replacing the draw line function? 
BR Achim

**Comment by MikhailPodkur** [comment]
Good day, Achim
> What was the reason for replacing the draw line function?
I'm sorry. When I debuging drawing error in checkbox code, then I think that it happend in line draw  function. Function was replaced, but error was not disappeared. And when that error was found in my code then I forgot to return previous realisation back.

And I have one question to you.
In _UG_PutChar had place translation:
switch ( bt )
   {
      case 0xF6: bt = 0x94; break; // ц
      case 0xD6: bt = 0x99; break; // Ц
      case 0xFC: bt = 0x81; break; // ь
      case 0xDC: bt = 0x9A; break; // Ь
      case 0xE4: bt = 0x84; break; // д
      case 0xC4: bt = 0x8E; break; // Д
      case 0xB5: bt = 0xE6; break; // µ
      case 0xB0: bt = 0xF8; break; // °
   }

Is it realy nesessary? Or those symbols needed pair exchange in fonts? I mean that symbol 0x94  must be at 0xF6 place and so on?
I'm interested in to remove that translation because cyrillic font have needed in 0xF6, 0xD6 etc symbols.

**Comment by MikhailPodkur** [comment]
Good night, dear co-programmer :)

You use so much raster fonts. What did you think if I add vector font support?

PS Merry christmas! And Happy new year!

**Comment by achimdoebler** [comment]
Hi Mikhail,
the char replacement in **_UG_PutChar** is not necessary but useful:
I didn't want to swap all char positions directly inside each font array, in order to maintain the original format. On the other hand, I wanted to ensure that e.g. UG_PutString(0,0,"ÄäÖöÜüµ"  prints correct chars. 

Sure, vector fonts would be nice - what do you think about just implementing a single vector char to firstly evaluate the pro and cons? 

I wish you also all the best: have a Merry Christmas and a Happy New Year!
Take care,

Achim

**Pull request closed without merging**
